apiVersion: v1
kind: Service
metadata:
  name: zeus-controller
spec:
  selector:
    app: zeus-controller
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-controller
  namespace: zeus
spec:
  selector:
    matchLabels:
      app: zeus-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: zeus-controller
    spec:
      containers:
        - name: zeus-controller
          image: ghcr.io/picus92/zeus-controller:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgres-config
